Renommer plaque en numero immatriculation sur les textes descriptifs …
histovec/histovec-beta pull request #1334
Opened 2022-09-16 16:30 UTC by alexrignault

…et afficher l'image en responsive

2022-09-21 14:36 UTC, lucas-ulivi commented on frontend/src/views/ProprietairePage.vue
> +          style="width:100%"
Mettre le css dans une class css. L'image me parait vraiment grande, surtout avec le format mobile, a voir si on diminue la taille.

2022-09-29 15:38 UTC, tonydugas requested changes

2022-09-29 15:38 UTC, tonydugas commented on frontend/src/views/ProprietairePage.vue
> +import '../assets/css/image.css'
Essayer de plutôt garder la même logique pour l'import de la ressource ('@/assets/css/image.css')

2022-09-29 15:38 UTC, tonydugas commented on frontend/src/views/ProprietairePage.vue
> +          src="../../src/assets/img/proprietaire.svg"
Essayer avec l'alias ("@/assets/img/proprietaire.svg")

2022-09-29 15:38 UTC, tonydugas commented on frontend/src/views/ProprietairePage.vue
> +          class="fr-img-responsive fr-pl-2v image-presentation__format"
Vérifier quel style est appliqué => console du navigateur

2022-09-30 15:00 UTC, tonydugas approved these changes

2022-09-30 15:04 UTC, merged