rendre les composants DSFRCard non cliquable et image accueil responsive
histovec/histovec-beta pull request #1335
Opened 2022-09-16 17:01 UTC by alexrignault

2022-09-21 14:36 UTC, lucas-ulivi commented on frontend/src/views/AccueilPage.vue
> +          style="width:100%"
Mettre le css dans une class css. L'image me parait vraiment grande, surtout avec le format mobile, a voir si on diminue la taille.

2022-09-21 14:37 UTC, lucas-ulivi commented on frontend/src/views/AccueilPage.vue
> +            <h4 class="fr-card__title">
Remplacer le h4 par un h3 pour respecter la hiérarchie des titres

2022-09-22 14:23 UTC, lucas-ulivi commented on frontend/src/views/AccueilPage.vue
> +            <h4 class="fr-card__title">
Up, on reste conforme a la spec : on garde le h4

2022-09-22 14:25 UTC, lucas-ulivi commented on frontend/src/views/AccueilPage.vue
> +      <div class="bordure fr-m-3 fr-p-2" >
Mettre la card dans un composant spécifique

2022-09-28 10:02 UTC, lucas-ulivi commented on frontend/src/views/AccueilPage.vue
> +.tailleImage {
Voir le commentaire sur cette pull request : https://github.com/histovec/histovec-beta/pull/1334

2022-09-30 15:55 UTC, tonydugas requested changes

2022-09-30 15:55 UTC, tonydugas commented on frontend/src/components/CarteDsfrNonCliquable.vue
> +      <div class="fr-card fr-card--no-arrow">
CarteDsfrNonCliquable doit permettre l'affichage d'une seule card non cliquable. Pour cela, conserver que la partie du template entre les lignes 45 à 56 avec la variabilisation des props titre, description et image. Déplacer la gestion de la liste des cards dans le composant AccueilPage.vue (lignes 42 à 44) pour gérer la liste qui y est propre (4 cards à afficher)

2022-09-30 15:55 UTC, tonydugas commented on frontend/src/views/AccueilPage.vue
> -      images: {
à reintégrer puisque on passera les images en paramètre de la carte

2022-10-05 13:41 UTC, lucas-ulivi approved these changes

2022-10-05 13:43 UTC, tonydugas approved these changes

2022-10-05 13:51 UTC, merged