rediriger vers une page erreur si erreur 500 aucune reponse du back
histovec/histovec-beta pull request #1336
Opened 2022-09-16 19:36 UTC by alexrignault

rediriger vers une page erreur si erreur 500 aucune reponse du back plus image responsive

2022-09-21 14:45 UTC, lucas-ulivi commented on frontend/src/views/AcheteurPage.vue
> +          style="width:100%"
Mettre le css dans une class css. L'image me parait vraiment grande, surtout avec le format mobile, a voir si on diminue la taille.

2022-09-21 14:47 UTC, lucas-ulivi requested changes

2022-09-21 14:47 UTC, lucas-ulivi commented on frontend/src/views/FAQPage.vue
> +          style="width:100%"
Idem

2022-09-21 14:47 UTC, lucas-ulivi commented on frontend/src/views/RapportPage.vue
> +          style="width:100%"
Idem

2022-09-21 14:47 UTC, lucas-ulivi commented on frontend/src/views/RapportPage.vue
> +          style="width:100%"
Idem

2022-09-28 10:01 UTC, lucas-ulivi commented on frontend/src/views/AcheteurPage.vue
> +.tailleImage {
Voir le commentaire sur cette pull request : https://github.com/histovec/histovec-beta/pull/1334

2022-09-28 10:01 UTC, lucas-ulivi commented on frontend/src/views/FAQPage.vue
> +.tailleImage {
Voir le commentaire sur cette pull request : https://github.com/histovec/histovec-beta/pull/1334

2022-09-28 10:01 UTC, lucas-ulivi commented on frontend/src/views/RapportPage.vue
> +.tailleImage {
Voir le commentaire sur cette pull request : https://github.com/histovec/histovec-beta/pull/1334

2022-09-30 16:03 UTC, tonydugas requested changes

2022-09-30 16:03 UTC, tonydugas commented on frontend/src/views/AcheteurPage.vue
> +      <div class="fr-content-media">
Séparer la gestion des images de la gestion des erreurs :
- fix_redirect_vers_page_erreur_si_erreur_500 = gestion des erreurs
- branche à créer = gestion des images sur FAQ RapportPage et AcheteurPage

2023-03-14 10:29 UTC, closed without merging