feat(): Ajout d'un alerte à la copie du lien de partage
histovec/histovec-beta pull request #1342
Opened 2022-09-27 14:18 UTC by lucas-ulivi

2022-10-06 10:27 UTC, tonydugas requested changes

2022-10-06 10:27 UTC, tonydugas commented on frontend/src/views/RapportPage.vue
> +  <alerte-component
Appeler le composant en PascalCase

2022-10-06 13:59 UTC, tonydugas requested changes

2022-10-06 13:59 UTC, tonydugas commented on frontend/src/components/AlerteComponent.vue
> +import {DsfrAlert} from '@gouvminint/vue-dsfr';
Pas sûr que cela soit nécessaire vu qu'on importe directement à la racine actuellement les composants (cf main.js)

2022-10-06 13:59 UTC, tonydugas commented on frontend/src/components/AlerteComponent.vue
> +  components: {DsfrAlert},
Si importé à la racine alors déjà "pré-déclaré"

2022-10-06 13:59 UTC, tonydugas commented on frontend/src/views/RapportPage.vue
> +    ouvrirAlertCopieLien() {
Une apparition d'alerte = une action => pour moi la méthode d'ouverture/fermeture devrait être agnostique du type d'action et on devrait valoriser l'action juste en amont de l'appel à l'alerte. Cela permet aujourd'hui de gérer le cas de la copie de lien puis demain le cas de la copie de code (même composant alerte dont le contenu sera fonction de l'action réalisée.

2022-10-10 15:00 UTC, lucas-ulivi commented on frontend/src/components/AlerteComponent.vue
> +    setTimeout(() => this.$emit('close'), 5000);
Après avoir testé, j'ai constaté que le processus se termine à la fermeture manuel de la notification. Donc pas de doublon d'appel de la fonction 'close'.

2022-10-11 14:15 UTC, tonydugas requested changes

2022-10-12 15:09 UTC, tonydugas requested changes

2022-10-12 15:09 UTC, tonydugas commented on frontend/src/views/RapportPage.vue
> +          this.ouvrirAlerte('Une erreur est survenue lors de la copie du ' + typeText + '.', 'error')
Pour être cohérent et explicite, je propose d'avoir le message suivant :
'Une erreur est survenue lors de la copie du ' + typeText + ' **partage**.'

2022-10-12 15:09 UTC, tonydugas commented on frontend/src/views/RapportPage.vue
> +          this.ouvrirAlerte('Le ' + typeText + ' de partage du rapport est copier dans le presse papier.', 'success')
'Le ' + typeText + ' de partage du rapport est **copié** dans le presse papier.'

2022-10-13 09:26 UTC, tonydugas approved these changes

2022-10-13 09:29 UTC, merged