fix(): Afficher la situation administrative pour un véhicule avec au moins 1 sinistre
histovec/histovec-beta pull request #1343
Opened 2022-09-27 15:50 UTC by alexrignault

item 089
Onglet synthese : afficher les sinistres si existant dans la colonne situation administrative 
Onglet situation administrative : colonne suspensions, effectuer un retour a la ligne si plusieurs suspensions

2022-09-30 14:03 UTC, lucas-ulivi requested changes

2022-09-30 14:03 UTC, lucas-ulivi commented on frontend/src/views/RapportPage.vue
> +
Est-ce que le  comportement est correction pour un véhicule qui n'a pas de sinistre ?

2022-09-30 14:03 UTC, lucas-ulivi commented on frontend/src/views/RapportPage.vue
> +
Retirer le saut de ligne

2022-10-12 09:12 UTC, lucas-ulivi approved these changes

2022-10-12 16:34 UTC, tonydugas requested changes

2022-10-12 16:34 UTC, tonydugas commented on frontend/src/views/RapportPage.vue
> +                  <!-- Commentaire: un ou plusieurs sinistres -->
vu ensemble : faire un retour arrière complet et modifier les conditions lignes 1244 et 1266

2022-10-13 11:43 UTC, tonydugas approved these changes

2022-10-13 11:45 UTC, merged