fix():  renommer carte grise en certificat d'immatriculation sur la page FAQ
histovec/histovec-beta pull request #1354
Opened 2022-10-10 09:21 UTC by alexrignault

index : 28bis

2022-10-10 13:57 UTC, lucas-ulivi approved these changes

2022-10-11 12:39 UTC, tonydugas requested changes

2022-10-11 12:39 UTC, tonydugas commented on frontend/src/views/FAQPage.vue
> +              Si vous n’êtes pas le titulaire de le certificat d'immatriculation en cours de validité, vous ne pouvez pas consulter directement les données HistoVec pour ce véhicule. Il vous est poss
le titulaire de le certificat d'immatriculation => le titulaire **du** certificat d'immatriculation

2022-10-12 09:58 UTC, tonydugas approved these changes

2022-10-12 10:00 UTC, merged