Anonymiser les données personnelles qui s'affichent dans les logs
histovec/histovec-beta pull request #1362
Opened 2022-10-28 16:03 UTC by alexrignault

item: 101

2022-10-31 13:57 UTC, lucas-ulivi requested changes

2022-10-31 13:57 UTC, lucas-ulivi commented on backend/src/plugins/public-api/handlers/report.js
> +  appLogger.debug(`-- [backend] immat ==> ${anonymeImmat}`)
`
appLogger.debug(`-- [backend] immat ==> ${anonymize(immat)}`)
`

Je te propose de faire comme ca sur les autres lignes également pour éviter d'utiliser de la mémoire

2022-10-31 13:57 UTC, lucas-ulivi commented on backend/src/util/anonymiserData.js
> +export const anonymize = (text, nbVisibleCharAtPrefixAndSuffix = 2) => {
J'ai vu que pour les noms et prénoms tu renseignes nbVisibleCharAtPrefixAndSuffix =1
Mais comment ca se passe pour les petits noms ? par Exemple Léa donnera L*a ? Je pense qu'il y a des règles de gestion a améliorer pour cette fonction.
Egalement si on laisse nbVisibleCharAtPrefixAndSuffix  = 2 pour un mot qui a 4 lettres maximum on aura un texte non anonymisé.

2022-11-04 11:30 UTC, tonydugas submitted a review, later dismissed

2022-11-04 11:30 UTC, tonydugas commented on backend/src/plugins/public-api/routes/reportCommon.js
> +      const anonymizedNom = nom ? anonymize(nom, 1) : nom
Extraire de la ligne 75 à 82 dans une fonction pour ne pas alourdir la lisibilité du traitement.

2022-11-04 11:30 UTC, tonydugas commented on backend/src/plugins/public-api/routes/reportCommon.js
> +      const anonymizedNom = nom ? anonymize(nom, 1) : nom
Plutôt que de créer une variable par champ, créer une variable objet dont on valorise des attributs et passer cet variable en tant que value dans le log.

2022-11-04 11:30 UTC, tonydugas commented on backend/src/plugins/public-api/routes/reportCommon.js
> +      syslogLogger.info({ key: 'payload_data', tag: logLabel, value: { alreadyHasIdAndKey, anonymizedNom, anonymizedPrenom, anonymizedRaisonSociale, anonymizedSiren, anonymizedNumeroImmatriculation,
Ajouter dans l'objet l'uuid à des fins d'investigation puisqu'on ne pourra pas s'appuyer sur les données nominatives (qui auront été anonymisées)

2022-11-04 11:30 UTC, tonydugas commented on backend/src/plugins/public-api/routes/reportCommon.js
> +      syslogLogger.info({ key: 'payload_data', tag: logLabel, value: { alreadyHasIdAndKey, anonymizedNom, anonymizedPrenom, anonymizedRaisonSociale, anonymizedSiren, anonymizedNumeroImmatriculation,
Ajouter également l'uuid sur le log qui possède la clé "payload_code" (ligne 67)

2022-11-04 11:30 UTC, tonydugas commented on backend/src/util/anonymiserData.js
> +export const anonymize = (text, nbVisibleCharAtPrefixAndSuffix = 2) => {
Revenir à l'ancienne version de la fonction "anonymize" (sans la condition) + créer une fonction spécifique pour les noms/prénoms qui pseudonymisera toutes les lettres sauf la première de chaque partie + appeler la nouvelle fonction pour les données d'identité (PP et PM)

2023-01-03 14:23 UTC, lucas-ulivi requested changes

2023-01-03 14:23 UTC, lucas-ulivi commented on backend/src/util/identiteLogAnonymiser.js
> +export const anonymizedIdentite = (identiteLog) => {
Tu peux mettre cette fonction dans le anonymiserData

2023-02-06 10:38 UTC, lucas-ulivi requested changes

2023-02-06 10:38 UTC, lucas-ulivi commented on backend/src/util/anonymiserData.js
> +export const anonymizeIdentite = (text) => {
On a deux fonction avec des noms similaire : anonymizeIdentite et anonymizedIdentite. Cette fonction a plutot un role d'anonymiser un text donc je propose de la renommer en anonymizeText et  anonymizedIdentite en anonymizeIdentite

2023-02-06 10:38 UTC, lucas-ulivi commented on backend/src/util/anonymiserData.js
> +  return anonymizedText
La fonction casse si on a un text avec plusieurs espaces a la suite, je propose d'utiliser un split pour faciliter la gestion du découpage du text.

2023-02-06 10:38 UTC, lucas-ulivi commented on backend/src/util/anonymiserData.js
> +export const anonymizedIdentite = (identiteLog) => {
retirer 'log' de la variable  identiteLog. La fonction peut etre utiliser pour d'autres situations

2023-02-22 09:45 UTC, lucas-ulivi approved these changes

2023-03-31 09:23 UTC, christophemorenosopra approved these changes

2023-03-31 09:24 UTC, merged