feat(): adaptation de la page d'accessibilité
histovec/histovec-beta pull request #1364
Opened 2022-11-15 14:48 UTC by lucas-ulivi

2022-11-15 15:58 UTC, alexrignault requested changes

2022-11-16 09:44 UTC, tonydugas requested changes

2022-11-16 09:44 UTC, tonydugas commented on frontend/src/views/AccessibilitePage.vue
>        </p>
IntelliJ râle de mon côté si ul est dans p et c'est parce que d'après la spec html ce n'est pas autorisé (ça marche mais ce n'est pas une bonne chose). Vue le traduit en un paragraphe vide , la liste puis un autre paragraphe vide => Il faut retirer les paragraphes qui englobent toutes les balises ul (résultats des tests, non conformités, techno, navigateurs/assistance, outils, pages testées, contact, voie de recours) + rajouter à la balise ul une classe pour gérer le margin bottom qui était réalisé à l'aide du paragraphe (https://gouvfr.atlassian.net/wiki/spaces/DB/pages/222396724/Espacement+-+Spacing#Espacement-verticaux ==> essayer "fr-mb-3w")

2022-11-16 09:44 UTC, tonydugas commented on frontend/src/views/AccessibilitePage.vue
> +          <li>Le taux moyen de conformité du service en ligne s’élève à 50%.</li>
La valeur de 50% provient de quelle source (pas trouvée dans le rapport mais j'ai peut-être mal vu) ? Si on n'a pas une quantification sûre, vu que dans le modèle cette ligne est facultative, on ne la met pas.

2022-11-16 09:44 UTC, tonydugas commented on frontend/src/views/AccessibilitePage.vue
> +          <li>Images</li>
Retour 1 : la liste est exhaustive alors que dans le rapport certaines parties ne nous concernent pas (ex : cadre) => ne mentionner que les éléments qui nous concernent ici
Retour 2 : on a les éléments mais pas les raisons => prévoir une phrase par item pour expliquer synthétiquement ce qui n'est pas conforme (ex : Images : gestion de l'attribut "alt" à améliorer pour distinguer des éléments pertinents des éléments de décoration)

2022-11-16 09:44 UTC, tonydugas commented on frontend/src/views/AccessibilitePage.vue
>        <h5 class="fr-blue-title">
On passe de h1 à h5 => c'est cohérent ? j'aurai plutôt vu 
h1 => Accessibilité
h2 => Introduction, Déclaration de conformité
h3 => tous les autres titres restants actuellement en h5

2022-11-16 09:44 UTC, tonydugas commented on frontend/src/views/AccessibilitePage.vue
> +          <li>validator.w3.org pour l'utilisation : Validateur du code</li>
Retour 1 : Réflexion faite, j'inverserai chaque élément de chaque item (en retirant le "pour l'utilisation") :
- Validateur de code : validator.w3.org
- etc.

Retour 2 : On pourrait même refaire une sous liste si une catégorie à plusieurs outils (ex: Outil d’évaluation de pages web) en précisant "plugin" après le nom de l'outil ce qui me paraît plus cohérent

Retour 3 : les 2 liens à matérialiser en tant que tels

2022-11-16 09:44 UTC, tonydugas commented on frontend/src/views/AccessibilitePage.vue
> +            Envoyer un courrier par la poste (gratuit, ne pas mettre de timbre) Défenseur des droits.<br />
rajouter après la ")" => " : " et passer à la ligne pour avoir l'adresse plus visible sinon c'est compliqué à lire

2022-11-16 16:55 UTC, alexrignault approved these changes

2022-11-16 16:57 UTC, merged