fix(RGAA-1.2): Enlever l'alt sur RapportPage (rapport acheteur et vendeur)
histovec/histovec-beta pull request #1373
Opened 2022-11-24 17:02 UTC by alexrignault

2022-11-28 09:36 UTC, lucas-ulivi requested changes

2022-11-28 09:36 UTC, lucas-ulivi commented on frontend/src/views/RapportPage.vue
> +      <ImagePresentation v-if="isRapportVendeur" :src="images.rapportVendeurSvg" alt="" />
On peut complétement supprimer l'attribut. Dans le composant ImagePresentation le alt n'est pas obligatoire et a une valeur par défaut à ''.

```suggestion
      <ImagePresentation v-if="isRapportVendeur" :src="images.rapportVendeurSvg" />
```

2022-11-28 09:36 UTC, lucas-ulivi commented on frontend/src/views/RapportPage.vue
> +      <ImagePresentation v-if="isRapportAcheteur" :src="images.rapportAcheteurSvg" alt="" />
Même remarque

```suggestion
      <ImagePresentation v-if="isRapportAcheteur" :src="images.rapportAcheteurSvg" />
```

2022-11-29 16:00 UTC, lucas-ulivi approved these changes

2022-12-08 15:50 UTC, tonydugas approved these changes

2022-12-08 15:51 UTC, merged