fix(RGAA-1.2): Enlever l'alt sur FAQPage
histovec/histovec-beta pull request #1374
Opened 2022-11-25 09:04 UTC by alexrignault

2022-11-28 09:37 UTC, lucas-ulivi requested changes

2022-11-28 09:37 UTC, lucas-ulivi commented on frontend/src/views/FAQPage.vue
> +      <ImagePresentation :src="image.faqSvg" alt="" />
On peut complétement supprimer l'attribut. Dans le composant ImagePresentation le alt n'est pas obligatoire et a une valeur par défaut à ''.

```suggestion
      <ImagePresentation :src="image.faqSvg" alt="" />
```
```suggestion
      <ImagePresentation :src="image.faqSvg" />
```

2022-11-29 16:01 UTC, lucas-ulivi approved these changes

2022-12-08 15:48 UTC, tonydugas approved these changes

2022-12-08 15:49 UTC, merged