fix(RGAA-11.10): Ajouter des attributs required sur les formulaires de PropreiairePage
histovec/histovec-beta pull request #1375
Opened 2022-11-25 13:58 UTC by alexrignault

2022-11-28 10:46 UTC, lucas-ulivi requested changes

2022-11-28 10:46 UTC, lucas-ulivi commented on frontend/src/views/ProprietairePage.vue
> +                  aria-errormessage="nom-particulier-SIV-erreur-message"
Pour tous les champs input, ajouter l'attribut aria-describedby avec la même valeur que pour aria-errormessage

```suggestion
                  aria-errormessage="nom-particulier-SIV-erreur-message"
                  aria-describedby="nom-particulier-SIV-erreur-message"
```

2022-11-29 16:03 UTC, lucas-ulivi approved these changes

2022-12-14 08:47 UTC, tonydugas requested changes

2022-12-14 08:47 UTC, tonydugas commented on frontend/src/views/ProprietairePage.vue
> +            Les champs marqués d'un astérisque sont obligatoires.
On retrouve 4 fois le même libellé dupliqué => s'appuyer sur une constante dans le fichier pour éviter les multiples impacts en cas de nécessité.

2023-01-09 09:14 UTC, tonydugas approved these changes

2023-01-09 09:19 UTC, merged