fix(RGAA-11.10): Ajouter des attributs required sur les formulaires de ContactPage
histovec/histovec-beta pull request #1376
Opened 2022-11-25 14:24 UTC by alexrignault

2022-11-28 10:42 UTC, lucas-ulivi requested changes

2022-11-28 10:42 UTC, lucas-ulivi commented on frontend/src/views/ContactPage.vue
> +          aria-errormessage="email-erreur-message"
Dans la doc du dsfr il y a également un attribut aria-describedby, j'en profiterais pour l'ajouterai également

```suggestion
          aria-errormessage="email-erreur-message"
          aria-describedby="email-erreur-message"
```

2022-11-28 10:42 UTC, lucas-ulivi commented on frontend/src/views/ContactPage.vue
> +          aria-errormessage="message-erreur-message"
Même remarque 
```suggestion
          aria-errormessage="message-erreur-message"
          aria-describedby="message-erreur-message"
```

2022-11-29 16:04 UTC, lucas-ulivi approved these changes

2022-12-13 16:56 UTC, tonydugas approved these changes

2022-12-13 16:56 UTC, merged