fix(RGAA-6.1): Ajouter un titre plus précis vers le lien de societe.com ProprietairePage
histovec/histovec-beta pull request #1377
Opened 2022-11-25 16:21 UTC by alexrignault

2022-11-28 09:44 UTC, lucas-ulivi requested changes

2022-11-28 09:44 UTC, lucas-ulivi commented on frontend/src/views/ProprietairePage.vue
>            Vous pouvez aussi l'obtenir sur ce
Je propose cette modification pour que le message soit plus clair.
Modifier également le mot "site" du lien par "societe.com"

```suggestion
          Vous pouvez aussi l'obtenir sur le site
```

2022-11-29 16:05 UTC, lucas-ulivi approved these changes

2022-12-14 08:27 UTC, tonydugas approved these changes

2022-12-14 08:28 UTC, merged