fix(RGAA-6.1): expliciter lien CritAir et supprimer redondance simplimmat
histovec/histovec-beta pull request #1386
Opened 2022-11-30 16:56 UTC by alexrignault

2022-12-06 09:16 UTC, tonydugas commented on frontend/src/views/RapportPage.vue
> +                    En savoir plus sur Crit'Air
Devra disparaître avec le rebase suite à la suppression du crit'air

2023-01-09 10:46 UTC, tonydugas requested changes

2023-01-09 10:46 UTC, tonydugas commented on frontend/src/views/RapportPage.vue
> +              alt=""
Inutile ?

2023-01-09 10:46 UTC, tonydugas commented on frontend/src/views/RapportPage.vue
> +          alt=""
Inutile ?

2023-01-09 10:46 UTC, tonydugas commented on frontend/src/views/RapportPage.vue
>              id="monAvisImage"
Peux-tu confirmer que suite au rebase et à la suppression en amont de la vignette Crit'air, les éléments devant être impactés le sont bien tous stp ?

2023-01-09 10:46 UTC, tonydugas commented on frontend/src/views/RapportPage.vue
> +            title="Lien vers jedonnemonavis.numerique.gouv.fr pour donner son avis sur la démarche HistoVec"
Comment tu es arrivé à la conclusion que c'est "jedonnemonavis.numerique.gouv.fr" qui faut mettre ici? Je demande parce que ce n'est pas le domaine visé par le lien qui vise "voxusagers.numerique.gouv.fr" et les 2 domaines précités mènent vers un troisième domaine qui est "observatoire.numerique.gouv.fr". L'important je pense que c'est le point d'arrivée qui doit être le même mais je suis curieux de savoir la source de l'information. 
Pour la valeur du titre, pas de souci pour laisser "jedonnemonavis.numerique.gouv.fr" parce qu'il est plus parlant que les 2 autres.

2023-01-12 09:42 UTC, alexrignault commented on frontend/src/views/RapportPage.vue
> +          alt=""
C'est un attribut requis pour la balise img et un critère pour la validation du test  1.2.1 du RGAA. https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#1.2.1

2023-01-12 09:43 UTC, alexrignault commented on frontend/src/views/RapportPage.vue
> +              alt=""
C'est un attribut requis pour la balise img et un critère pour la validation du test  1.2.1 du RGAA. https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#1.2.1

2023-01-12 09:54 UTC, alexrignault commented on frontend/src/views/RapportPage.vue
>              id="monAvisImage"
Le Crit'air n'intervient plus sur RapportPage

2023-01-12 09:59 UTC, alexrignault commented on frontend/src/views/RapportPage.vue
> +                    En savoir plus sur Crit'Air
Il a bien disparu

2023-02-27 16:53 UTC, lucas-ulivi approved these changes

2023-03-14 15:25 UTC, merged