fix(RGAA-12.7): Lien d'accès rapide
histovec/histovec-beta pull request #1397
Opened 2022-12-12 09:33 UTC by alexrignault

2023-01-03 11:04 UTC, lucas-ulivi approved these changes

2023-01-09 11:16 UTC, tonydugas requested changes

2023-01-09 11:16 UTC, tonydugas commented on frontend/src/App.vue
> +  <LienEvitement />
J'ai l'impression que quelque soit le lien que je choisis cela me ramène toujours au même endroit à savoir au centre de la page visiblement. 
J'ai testé en format classique (navigateur) et un format responsive. En format responsive par exemple quand je choisis pied de page => il revient au centre sans me le montrer (donc en n'allant pas assez bas...)
Et la meilleure, c'est que sur le site du design de l'état, et bien j'ai le même comportement...

2023-01-09 11:16 UTC, tonydugas commented on frontend/src/App.vue
> +  <LienEvitement />
Donc en l'état je n'ai rien contre le code qui a été produit ici mais... il ne fonctionne pas pour moi 😞

2023-03-14 16:07 UTC, lucas-ulivi approved these changes

2023-03-14 17:07 UTC, merged