fix(RGAA-7.4): remonter en haute de page apres une redirection
histovec/histovec-beta pull request #1398
Opened 2022-12-12 16:21 UTC by lucas-ulivi

2023-01-09 09:11 UTC, alexrignault approved these changes

2023-01-09 11:22 UTC, tonydugas requested changes

2023-01-09 11:22 UTC, tonydugas commented on frontend/src/router/index.js
> -      behavior: 'smooth',
Je ne comprends pas cette modification... Quel est le lien avec le retour RGAA 7.4 ?

2023-02-16 12:46 UTC, lucas-ulivi commented on frontend/src/router/index.js
> -      behavior: 'smooth',
Le problème relevé par le point est que l'utilisateur n'est pas averti du rechargement de la page. Pour la correction il faut positionner l'utilisateur sur le titre principal de la page.
C'est ce que fait la fonction scrollBehavior mais le paramètre behavior  smooth présente une anomalie dans son fonctionnement et bloque le scroll en haut de page par moment. Je n'ai pas trouvé d'autres solutions que de le supprimer.

2023-03-01 09:46 UTC, lucas-ulivi commented on frontend/src/router/index.js
> -      behavior: 'smooth',
UP : avec des recherches supplémentaire, je me suis rendu compte que le problème est présent sur firefox et pas sur chrome. J'ai fini par trouver une solution en ajoutant un élément en target pour le scroll

2023-03-14 15:27 UTC, merged