fix(RGAA-7.1): ajout du focus sur l'apparition du formulaire des imma…
histovec/histovec-beta pull request #1417
Opened 2023-02-07 10:52 UTC by lucas-ulivi

…triculations

2023-02-16 09:29 UTC, alexrignault requested changes

2023-02-16 09:29 UTC, alexrignault commented on frontend/src/views/ProprietairePage.vue
> +      sleep(100).then(() => {
Le délai d'activation du focus pour les DSFRTabs est trop court, l'animation de changement d'onglet ne se termine pas ce qui fait sauter les boutons. Avec 300 ms les 2 actions peuvent se faire successivement.

2023-02-16 09:29 UTC, alexrignault commented on frontend/src/views/ProprietairePage.vue
> +      sleep(100).then(() => {
Même chose

2023-02-28 08:44 UTC, alexrignault approved these changes

2023-02-28 10:26 UTC, christophemorenosopra commented
Pas fan du sleep, as-tu essayé avec nexttick ?
https://vuejs.org/api/general.html#nexttick

2023-03-15 10:15 UTC, merged